version: 1.0.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: >-
    cd ./src

    nuget restore
build:
  project: c:\projects\essenbee-bot\src\Essebee.Bot.sln
  verbosity: minimal
test_script:
- cmd: >-
    cd c:\projects\essenbee-bot/src/UnitTests

    nuget install Appveyor.TestLogger -Version 2.0.0

    cd ..

    dotnet test --no-build --no-restore --test-adapter-path:. --logger:Appveyor c:\projects\essenbee-bot/src/UnitTests